### PR TITLE
Switch CI to Github actions

### PR DESCRIPTION
**Pull request by odow**

### CODE REVIEW

**Comment by odow** [comment]
This was surprisingly easy...

**Comment by joaquimg** [comment]
Do you have any step by step for the secret files?

**Comment by odow** [comment]
> Do you have any step by step for the secret files?

Settings > Secrets > New Secret.

The nice thing is that you don't have the base64 encode the URL anymore and escape the necessary characters 😄

**Comment by joaquimg** [comment]
Nice! Thanks and great work!

**Pull request merged**
