### PR TITLE
Fix local discovery of CPLEX 20.1

### PR DESCRIPTION
**Pull request by metab0t**

### CODE REVIEW

**Comment by metab0t** [comment]
I test this on Windows 10 and it works fine but CI fails. 
Multiversion support is hard 😢

**Comment by dourouc05** [comment]
In my previous PR, I had added a third version to look for, on line 35: https://github.com/jump-dev/CPLEX.jl/pull/348/files#diff-708e1c220f34be9ffbf04c0619b1f1a56388096c1df2b95603950d7adc80feaaL35

Also, don't forget to update the messages in the same file.

(This part was missing in #349…)

**Comment by odow** [comment]
Yes, this is my fault. I'll sort it.

**Comment by dourouc05** [comment]
Would it be possible to tag a version with this fix, so that new users don't face the same bug?

**Pull request closed without merging**
